random_seed: 15
rollout_length: 2500 #1000000
batch_size: 40
num_batches: 1
deter: False
save_pos: True
save_frequency: 1 #100
dataname: hbv
model_dir: ${oc.env:MODEL_DIR}/hbv_pnr
save_dir: ${model_dir}

ld_kwargs:
  step_per_sigma: 5
  step_size: 0.0001

data:
  _target_: graphwm.data.data.HBVDataset
  directory: ${oc.env:HBV_TEST_DATASET_DIR}
  split: ${oc.env:PROJECT_ROOT}/splits/hbv/test.txt ######
  mode: rollout
  recursive_metis: False

hydra:
  run:
    dir: ${save_dir}